
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtbhwljvtdpqkituaggx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0Ymh3bGp2dGRwcWtpdHVhZ2d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MjU1NzksImV4cCI6MjA1ODQwMTU3OX0.YVlj3-V896d_PLQ-ks-AbIlYMMMYGD02Rd4xoracXcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'talkfusion-auth-token',
  }
});
